fixing namespace handling to work as originally intended
heroku/configerator pull request #12
Opened 2017-02-03 18:40 UTC by jmervine

You should be able to set `FOO` or `NAMESPACE_FOO` and fetch via `Config.namespace_foo` when doing something like:

```ruby
namespace :namespace do
    optional :foo
end
```

Currently only setting `FOO` gives you a value.

cc @joshuatobin @reidmix

2017-02-07 16:32 UTC, jmervine commented on test/configerator_test.rb
> -    ns1: 'ns1',
@reidmix using `test_ns{1,2}` and `ns{1,2}` is what masked the bug. =P

2017-02-07 16:34 UTC, jmervine commented on lib/configerator/configerator.rb
> +      instance_eval "def #{meth}; @#{meth} || (raise 'keys not set: \"#{pfxd}\" or \"#{orig}\"' unless #{error_on_load}) end"
@reidmix Because only one of the two keys are expected to be set, perhaps this should be `key not set:` and not `keys not set`, in spite of it referencing two keys. Thoughts?

2017-02-08 16:35 UTC, lexelby requested changes

2017-02-08 16:35 UTC, lexelby commented on lib/configerator/configerator.rb
> +      instance_eval "def #{meth}; @#{meth} || (raise 'keys not set: \"#{pfxd}\" or \"#{orig}\"' unless #{error_on_load}) end"
I vote for singular.

2017-02-08 16:35 UTC, lexelby commented on lib/configerator/configerator.rb
> +  def prefixize_key(key)
IMO the "ize" is unnecessary: "prefix" is already a verb.  `prefix_key` should be sufficient.

2017-02-08 16:35 UTC, lexelby commented on lib/configerator/configerator.rb
> +              # handle one possible keys
s/keys/key/

2017-02-08 16:35 UTC, lexelby commented on test/configerator_test.rb
> +    end
Seems kind of repetitive, having to run `Config.required :test_missing` twice to test both the exception type and message.  Perhaps this?

```
begin
  Config.required :test_missing
rescue KeyError => ex
  assert_equal ex.message, 'key not found: "TEST_MISSING"'
else
  fail
end
```

2017-02-08 17:01 UTC, jmervine commented on test/configerator_test.rb
> +    end
Oh, that's nifty! Didn't know about `fail`.

2017-02-08 17:07 UTC, jmervine commented
@lexelby All comments address. Thanks for the excellent feedback.

2017-02-09 14:40 UTC, lexelby commented on test/configerator_test.rb
>      rescue => ex
Still need to specify `KeyError` here to make sure it raises the right exception.

2017-02-09 14:41 UTC, lexelby commented on test/configerator_test.rb
>      end
Is it possible to do the same begin/rescue/else thing here?

2017-02-09 16:17 UTC, lexelby approved these changes

2017-02-09 16:17 UTC, lexelby commented
:+1:

2017-02-10 23:49 UTC, jmervine commented
Based on a conversation with @reidmix, I'm going to update this so only `NAMESPACE_FOO` is supported and not `FOO`, when using namespaces by default. Disabling prefix when defining the  namespace will omit the requirement (and support) for the `NAMESPACE_`.

2017-02-13 16:05 UTC, jmervine commented
@reidmix Addressed comments from our previous discussion. Switch from minitest to rspec. I found the previous test suite hard to parse and it was leaving me feel less than confident in the tests. Also, because this is a gem, I updated travis to test against all 2.x versions of ruby.

2017-02-16 18:32 UTC, reidmix commented
@jmervine awesome on rspec -- yeah i was super lacking on tests plus I'm not always so nimble on minitest.

2017-02-16 19:40 UTC, reidmix requested changes
This is looking really good -- I really like what you did with the tests. 

Most of my comments are around simplifying the code more than anything.

2017-02-16 19:40 UTC, reidmix commented on .travis.yml
> +script: make spec
is it weird we're using `make`?

2017-02-16 19:40 UTC, reidmix commented on lib/configerator/configerator.rb
> +    key = "#{@prefix}#{key}" if defined?(@prefix) && !@prefix.nil? && @prefix != ""
I believe you can safely do `if @prefix` to simplify and get what you're looking for. 

It'll return `nil` if its undefined.
If it's an empty string, it won't change the `key`.

2017-02-16 19:40 UTC, reidmix commented on lib/configerator/configerator.rb
> +  def stringify_key(key)
I'd change the name here because its doing more than stringifying.  maybe `build_key`?

2017-02-16 19:40 UTC, reidmix commented on lib/configerator/configerator.rb
> +  def fetch_env(key, error_on_load: false, default: nil)
I don't think the `default` handling should be in this method, primarily because it's for one usecase (using `override`) and pushing it into this method complicates this method in subtle ways. 

The `error_on_load` functionality is no longer being executed quite the same way.  It's what `ENV.fetch` was doing when it raised an error if the key didn't exist, which is different from the value being `nil` (I'm realizing your change was done to help handle the case of applying the `default` values). 

My suggestion is to move it back to using `ENV.fetch` and let it do the error raising and not raise the error ourself here.   Then in `override` apply the default there (I'll make a note of it.)

2017-02-16 19:40 UTC, reidmix commented on lib/configerator/configerator.rb
> +    value = cast(fetch_env(name, default: default), method)
See my longer note on `fetch_env` -- I think we can simplify `fetch_env` if we apply the default inline here:

```ruby
    value = cast(fetch_env(name) || default, method)
```

2017-02-16 19:40 UTC, reidmix commented on lib/configerator/configerator.rb
> +    value = fetch_env(name, error_on_load: error_on_load)
I'd probably make this look more like `optional` & `override` when it gets the value, for consistency:
```ruby
value = cast(fetch_env(name, error_on_load: error_on_load), method)
```

2017-02-16 19:40 UTC, reidmix commented on lib/configerator/configerator.rb
> +    return unless @is_namespace
I don't think it hurts to have `@processed` get created if its not a namespace -- what you have here to check if it's for `@is_namespace` is more correct (for sure!) but I don't think you really need it.  the `@is_namespace` check doesn't really offer anything.  `@processed` gets cleared out every time `namespace` is called, so it stays tidy. 

Personally, I wouldn't worry about it and get rid of `@is_namespace`

2017-02-16 19:40 UTC, reidmix commented on spec/configerator_spec.rb
> +  let(:config) { Module.new { extend Configerator } }
sweet!

2017-02-16 19:40 UTC, reidmix commented on spec/configerator_spec.rb
> +    it "errors when missing required value" do
I'd also do a test for when `FOO` is not in the environment at all.

2017-02-16 19:40 UTC, reidmix commented on spec/configerator_spec.rb
> +    it "accepts missing value" do
I'd also do a test for when FOO is not in the environment at all.

2017-02-16 19:40 UTC, reidmix commented on spec/configerator_spec.rb
> +      with_environment foo: nil do
I'd also do a test for when FOO is not in the environment at all.

2017-02-16 19:40 UTC, reidmix commented on spec/configerator_spec.rb
> +      end
👍

2017-02-16 19:40 UTC, reidmix commented on spec/spec_helper.rb
> +end
I really like how this turned out in the tests, it looks really nice 👍

2017-02-16 19:59 UTC, jmervine commented on spec/configerator_spec.rb
> +    it "errors when missing required value" do
Setting it to `nill` is how you emulate it not being in the environment. If I don't remember it all all the `allow_any_instance_of` throws an error b/c something is called that's not expected. I might be able to do that by not stubbing the environment for that test, but then if someone happens to have `FOO` set, it will break the spec.

2017-02-16 20:04 UTC, jmervine commented on lib/configerator/configerator.rb
> +  def fetch_env(key, error_on_load: false, default: nil)
Yeah, I was on the fence on this, I'll revisit.

2017-02-16 20:45 UTC, jmervine commented on .travis.yml
> +script: make spec
Yeah, it tends to be my goto for simple things, I'll switch it to rake at some point, but perhaps not in this PR.

2017-02-16 20:50 UTC, jmervine commented on lib/configerator/configerator.rb
> +    key = "#{@prefix}#{key}" if defined?(@prefix) && !@prefix.nil? && @prefix != ""
I was trying to catch the `""` condition as well, but I think that's overkill. Good call here.

2017-02-16 21:58 UTC, reidmix commented on spec/configerator_spec.rb
> +    it "errors when missing required value" do
what if you don't mock anything?  that should do it right?

2017-02-17 17:04 UTC, jmervine commented on spec/configerator_spec.rb
> +    it "errors when missing required value" do
Yeah, oddly, initially I was getting errors with that, but I think that was in a previous iteration. I'm not sure what I changed to make it work, but that's what I'm doing now and it looks good.

2017-02-17 23:56 UTC, reidmix commented on lib/configerator/configerator.rb
> +    key = "#{@prefix}#{key}" if @prefix
i'm realizing we don't even need the `if @prefix` because if it's nil or blank, we'd never see it. 
Something to simplify for the future, not required to change now.

2017-02-17 23:58 UTC, reidmix approved these changes
LGTM 👍

2017-02-18 19:47 UTC, merged